services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    # ... doesn't work
    Videostation\Command:
        tags: ['console.command']

    # ... doesn't work
    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['console.command']